import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from './MainLayout.module.css'
import Navbar from '../Navbar'

const inter = Inter({ subsets: ['latin'] })

const MainLayout = ({ children }: { children: any }) => {
  return (
    <>
      <div className={styles.main}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Navbar />
        <main className={`${styles.main} ${inter.className}`}>
          {children}
        </main>
      </div>
    </>
  )
}

export default MainLayout
